# Generated by Django 4.1.7 on 2023-04-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=150)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорию", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name="Coments",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="blog.post",
            ),
        ),
    ]
